name: Comment
on:
  workflow_dispatch:

jobs:
  notify-inactive-discussions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Notify Inactive Discussions Older Than 60 Seconds
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Define the category name
        CATEGORY_NAME="Questions about config, custom styles and templates"
        
        # Fetch discussions
        gh api graphql -f query='
        query($owner: String!, $repo: String!) {
          repository(owner: $owner, name: $repo) {
            discussions(first: 100, orderBy: {field: UPDATED_AT, direction: ASC}) {
              nodes {
                id
                title
                url
                updatedAt
                category {
                  name
                }
                labels(first: 10) {
                  nodes {
                    name
                  }
                }
              }
            }
          }
        }' -f owner="MrBearPresident" -f repo="Bubble-Card" > discussions.json
        
        # Process discussions and create comments
        cat discussions.json | \
        jq --arg category "$CATEGORY_NAME" -r '.data.repository.discussions.nodes[] | 
            select(.category.name == $category) | 
            select((now - (.updatedAt | fromdateiso8601)) > 60) | 
            {id: .id, url: .url}' > filtered_discussions.json
        
        # Add comments to each discussion
        while IFS= read -r line; do
          discussion_id=$(echo "$line" | jq -r '.id')
          discussion_url=$(echo "$line" | jq -r '.url')
          
          # Create comment using GraphQL mutation
          gh api graphql -f query='
          mutation($discussionId: ID!, $body: String!) {
            addDiscussionComment(input: {discussionId: $discussionId, body: $body}) {
              comment {
                id
              }
            }
          }' -f discussionId="$discussion_id" -f body="This discussion has been inactive for over 60 seconds. Please update with any additional information if your question hasn't been resolved."
          
          echo "Added comment to discussion: $discussion_url"
        done < <(jq -c '.[]' filtered_discussions.json)
